votes/urls.py
from django.urls import path

from . import views

app_name = 'votes'
urlpatterns = [
    path('', views.Decisions.as_view(), name='decisions'),
    path('create/', views.DecisionCreate.as_view(), name='create'),
    path('invitations/', views.Invitations.as_view(), name='invitations'),
    path('invitations/create/', views.InvitationCreate.as_view(), name='invite'),
    path('join/', views.JoinTeam.as_view(), name='join'),
    path('owned/', views.DecisionsOwned.as_view(), name='owned'),
    path('registration/', views.Registration.as_view(), name='registration'),
    path('registration/done/', views.RegistrationDone.as_view(), name='registration-done'),
    path('results/', views.Results.as_view(), name='results'),
    path('teams/', views.Teams.as_view(), name='teams'),
    path('<int:pk>/', views.DecisionInfo.as_view(), name='info'),
    path('<int:pk>/result/', views.ResultInfo.as_view(), name='result'),
    path('<int:pk>/vote/', views.VoteCreate.as_view(), name='vote'),
]

votes/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


def get_all_friends(self: User):
    teams_pk = self.teams.values_list('pk', flat=True)
    members_pk = Team.objects.filter(pk__in=teams_pk).values_list('members', flat=True).distinct()
    return User.objects.filter(pk__in=members_pk)


User.add_to_class("friends", get_all_friends)


class Decision(models.Model):
    subject = models.CharField(max_length=255)
    author = models.ForeignKey(User, related_name='decisions', on_delete=models.SET_NULL, null=True)
    voters = models.ManyToManyField(User, related_name='elections', blank=True)
    start = models.DateTimeField()
    end = models.DateTimeField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.subject}"

    def pending_voters(self):
        voters = []
        for user in self.voters.all():
            votes = Vote.objects.filter(user=user, option__in=self.options.all())
            if not votes.count():
                voters.append(user)

        return voters

    def state(self):
        now = timezone.now()

        if not self.pending_voters():
            # all voters have voted
            return {
                'code': "closed",
                'color': "danger",
                'icon': "fas fa-lock",
            }

        if now < self.start:
            # voting not started
            return {
                'code': "pending",
                'color': "warning",
                'icon': "fas fa-clock",
            }

        if self.start <= now < self.end:
            # voting possible
            return {
                'code': "open",
                'color': "success",
                'icon': "fas fa-vote-yea",
            }

        # voting closed
        return {
            'code': "closed",
            'color': "danger",
            'icon': "fas fa-lock",
        }


class Option(models.Model):
    decision = models.ForeignKey(Decision, related_name='options', on_delete=models.CASCADE)
    text = models.CharField(max_length=50)

    def __str__(self):
        return f"{self.text}"


class Vote(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    option = models.ForeignKey(Option, related_name='votes', on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.get_full_name()}"

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user', 'option'], name='unique_vote'),
        ]


class Team(models.Model):
    name = models.CharField(max_length=150)
    slug = models.SlugField()
    members = models.ManyToManyField(User, related_name='teams', through='Membership')
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Invitation(models.Model):
    token = models.SlugField(unique=True)
    teams = models.ManyToManyField(Team, related_name='invitations')
    expiry = models.DateTimeField()
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)


class Membership(models.Model):
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    invitation = models.ForeignKey(Invitation, on_delete=models.SET_NULL, null=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['team', 'user'], name='unique_member'),
        ]

votes/views.py
import secrets

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.core.exceptions import PermissionDenied
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.utils import timezone
from django.views.generic import ListView, DetailView, TemplateView
from django.views.generic.edit import FormView, CreateView
from secrets import token_urlsafe

from .forms import DecisionForm, VoteForm, InvitationForm, JoinTeamForm, RegistrationForm
from .models import Decision, Option, Invitation, Team, Membership


class DecisionCreate(LoginRequiredMixin, FormView):
    template_name = 'votes/create.html'
    form_class = DecisionForm
    success_url = reverse_lazy('votes:decisions')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.save()
        for text in ["Dafür", "Dagegen", "Enthaltung"]:
            option = Option.objects.create(decision=form.instance, text=text)
            option.save()
        return super().form_valid(form)


class DecisionInfo(LoginRequiredMixin, DetailView):
    template_name = 'votes/info.html'
    model = Decision
    form_class = VoteForm


class Decisions(LoginRequiredMixin, ListView):
    model = Decision
    template_name = 'votes/list.html'

    def get_queryset(self):
        decisions = Decision.objects.filter(
            voters__in=[self.request.user],
            end__gt=timezone.now(),
        ).order_by('start')
        return decisions

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Offene Abstimmungen"
        return context


class DecisionsOwned(LoginRequiredMixin, ListView):
    model = Decision
    template_name = 'votes/list.html'

    def get_queryset(self):
        return Decision.objects.filter(author=self.request.user).order_by('-end')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Eigene Abstimmungen"
        return context


class Results(LoginRequiredMixin, ListView):
    model = Decision
    template_name = 'votes/list.html'
    queryset = Decision.objects.filter(end__lt=timezone.now()).order_by('-end')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Abgeschlossene Abstimmungen"
        return context


class ResultInfo(LoginRequiredMixin, DetailView):
    template_name = 'votes/info.html'
    model = Decision

    def get(self, request, *args, **kwargs):
        decision = get_object_or_404(Decision, pk=self.kwargs['pk'])
        if decision.state()['code'] != 'closed':
            raise PermissionDenied()
        return super().get(request, *args, **kwargs)


class VoteCreate(LoginRequiredMixin, FormView):
    template_name = 'votes/vote.html'
    form_class = VoteForm
    success_url = reverse_lazy('votes:decisions')

    def get_context_data(self, **kwargs):
        decision = get_object_or_404(Decision, pk=self.kwargs['pk'])

        context = super().get_context_data(**kwargs)
        context['decision'] = decision
        context['entitled_to_vote'] = self.request.user in decision.voters.all()
        context['user_has_voted'] = self.request.user not in decision.pending_voters()
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['decision'] = Decision.objects.get(pk=self.kwargs['pk'])
        return kwargs

    def post(self, request, *args, **kwargs):
        decision = Decision.objects.get(pk=self.kwargs['pk'])

        if decision.state()['code'] != 'open':
            # voting not allowed
            raise PermissionDenied()

        if self.request.user not in decision.voters.all():
            # user not entitled to vote
            raise PermissionDenied()

        if self.request.user not in decision.pending_voters():
            # user already voted
            raise PermissionDenied()

        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.save()
        return super().form_valid(form)


class Invitations(LoginRequiredMixin, ListView):
    model = Invitation
    template_name = 'votes/invitations.html'

    def get_queryset(self):
        return Invitation.objects.exclude(
            teams__in=Team.objects.exclude(members__exact=self.request.user),
        ).order_by('-created')


class InvitationCreate(LoginRequiredMixin, FormView):
    template_name = 'votes/invite.html'
    form_class = InvitationForm
    success_url = reverse_lazy('votes:invitations')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        form.instance.token = secrets.token_urlsafe(16)
        form.instance.creator = self.request.user
        form.save()
        return super().form_valid(form)


class Teams(LoginRequiredMixin, ListView):
    model = Team
    template_name = 'votes/teams.html'


class JoinTeam(LoginRequiredMixin, FormView):
    template_name = 'votes/join.html'
    form_class = JoinTeamForm
    success_url = reverse_lazy('votes:invitations')

    def form_valid(self, form):
        invitation = Invitation.objects.get(token=form.cleaned_data['token'])
        for team in invitation.teams.all():
            membership = Membership(
                team=team,
                user=self.request.user,
                invitation=invitation,
            )
            membership.save()

        return super().form_valid(form)


class Registration(CreateView):
    model = User
    template_name = 'votes/registration.html'
    form_class = RegistrationForm
    success_url = reverse_lazy('votes:registration-done')

    def get_initial(self):
        initial = super().get_initial()
        initial['token'] = self.request.GET.get('token')
        return initial

    def form_valid(self, form):
        # generate generic password
        secret = token_urlsafe(16)  # TODO drop generic password generation

        # update user profile
        form.instance.set_password(secret)
        form.instance.save()

        # join teams
        invitation = Invitation.objects.get(token=form.cleaned_data['token'])
        for team in invitation.teams.all():
            membership = Membership(
                team=team,
                user=form.instance,
                invitation=invitation,
            )
            membership.save()

        form.send_email(self.request, secret)
        return super().form_valid(form)


class RegistrationDone(TemplateView):
    template_name = 'votes/registration_done.html'

votes/templates/votes/base.html
{% extends 'faking/base.html' %}

{% block body %}
    {% include 'votes/navigation.html' %}

    <section class="section">
        <div class="container">
            {% block content %}{% endblock %}
        </div>
    </section>
{% endblock %}

votes/templates/votes/info.html
{% extends 'votes/base.html' %}

{% block content %}
    <div class="box content">
        <h1 class="title is-4 has-text-primary">Abstimmung {{ decision.id }}</h1>

        <p class="heading is-size-6 has-text-centered">Details</p>
        <div class="block">
            <div class="columns is-multiline">
                <p class="column is-12">
                    <strong>Gegenstand</strong>
                    <br>
                    {{ decision.subject }}
                </p>

                <p class="column is-6">
                    <strong>Ersteller:in</strong>
                    <br>
                    {{ decision.author.get_full_name }}
                </p>

                <p class="column is-6">
                    <strong>Datum</strong>
                    <br>
                    {{ decision.created }}
                </p>
            </div>
        </div>

        <p class="heading is-size-6 has-text-centered">Stimmberechtigte Personen</p>
        <div class="block">
            <ul class="list-unstyled">
                {% for voter in decision.voters.all %}
                    <li>{{ voter.get_full_name }}</li>
                {% endfor %}
            </ul>
        </div>

        <p class="heading is-size-6 has-text-centered">Zeitraum der Abstimmung</p>
        <div class="block">
            <div class="columns">
                <p class="column">
                    <strong>Beginn</strong>
                    <br>
                    {{ decision.start }}
                </p>

                <p class="column">
                    <strong>Ende</strong>
                    <br>
                    {{ decision.end }}
                </p>
            </div>
        </div>

        {% with path=request.resolver_match.url_name %}
            <p class="heading is-size-6 has-text-centered">
                {% if path == 'result' %}
                    Ergebnis
                {% else %}
                    Wählbare Optionen
                {% endif %}
            </p>
            <div class="block">
                <table class="table">
                    <tbody>
                    {% for option in decision.options.all %}
                        <tr>
                            <th>{{ forloop.counter }}</th>
                            <td>{{ option.text }}</td>
                            {% if path == 'result' %}
                                <td>{{ option.votes.count }} Stimme(n)</td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>

            {% if path != 'result' %}
                <div class="block">
                    {% if decision.state.code == 'closed' %}
                        <a class="button is-info is-fullwidth" href="{% url 'votes:result' decision.id %}">Zum
                            Ergebnis</a>
                    {% else %}
                        <a class="button is-primary is-fullwidth" href="{% url 'votes:vote' decision.id %}">Zur
                            Stimmabgabe</a>
                    {% endif %}
                </div>
            {% endif %}
        {% endwith %}
    </div>
{% endblock %}

votes/templates/votes/invitations.html
{% extends 'votes/base.html' %}

{% load static %}

{% block scripts %}
    {{ block.super }}
    <script src="{% static 'votes/js/copy-link.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="notification">
        <button class="delete"></button>
        Es werden nur Einladungen für Organe angezeigt, bei welchen du selbst Mitglied bist.
    </div>

    <div class="box">
        <h1 class="title is-4">Alle Einladungen</h1>

        <table class="table is-fullwidth">
            <thead>
            <tr>
                <th>ID</th>
                <th>Token</th>
                <th>Organ(e)</th>
                <th>Gültig bis</th>
                <th>Ersteller:in</th>
                <th>Erstellt am</th>
            </tr>
            </thead>
            <tbody>
            {% for invitation in invitation_list %}
                <tr>
                    <td>{{ invitation.id }}</td>
                    <td>
                        <div class="field has-addons">
                            <div class="control">
                                <input class="input" type="text" value="{{ invitation.token }}" readonly>
                            </div>
                            <div class="control">
                                <button class="button copy-link" data-tooltip="Copied!">
                                <span class="icon">
                                    <i class="fas fa-copy"></i>
                                </span>
                                </button>
                            </div>
                        </div>
                    </td>
                    <td>
                        <ul>
                            {% for team in invitation.teams.all %}
                                <li>{{ team.slug }}</li>
                            {% endfor %}
                        </ul>
                    </td>
                    <td>{{ invitation.expiry }}</td>
                    <td>{{ invitation.creator.get_full_name }}</td>
                    <td>{{ invitation.created }}</td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="5">Es wurden noch keine Einladungen erstellt.</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

votes/templates/votes/invite.html
{% extends 'votes/base.html' %}

{% load static %}

{% block scripts %}
    {{ block.super }}
    <script src="{% static 'votes/js/luxon.min.js' %}"></script>
    <script src="{% static 'votes/js/selection-buttons.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="notification">
        <button class="delete"></button>
        Du kannst nur Einladungen für Organe erstellen, bei welchen du selbst Mitglied bist.
    </div>

    <div class="box">
        <h1 class="title is-4">Neue Einladung erstellen</h1>

        <form method="post">
            {% csrf_token %}

            <div class="field">
                <label class="label" for="id_teams">{{ form.teams.label }}</label>

                <div class="control">
                    <ul id="id_teams">
                        {% for checkbox in form.teams %}
                            <li>
                                <label class="checkbox" for="{{ checkbox.id_for_label }}">
                                    {{ checkbox.tag }}
                                    {{ checkbox.choice_label }}
                                </label>
                            </li>
                        {% endfor %}
                    </ul>
                </div>

                {% for error in form.teams.errors %}
                    <p class="help is-danger">{{ error }}</p>
                {% endfor %}
            </div>

            <div class="field">
                <label class="label" for="{{ form.expiry.id_for_label }}">{{ form.expiry.label }}</label>

                {{ form.expiry }}

                <div class="buttons has-addons mb-0">
                    <button type="button" class="button choose-value" value="8">8 Stunden</button>
                    <button type="button" class="button choose-value" value="24">24 Stunden</button>
                    <button type="button" class="button choose-value" value="168">1 Woche</button>
                </div>

                {% for error in form.expiry.errors %}
                    <p class="help is-danger">{{ error }}</p>
                {% endfor %}
            </div>

            <div class="field">
                <div class="control">
                    <button type="submit" class="button is-primary">Erstellen</button>
                </div>

                {% for error in form.non_field_errors %}
                    <p class="help is-danger">{{ error }}</p>
                {% endfor %}
            </div>
        </form>
    </div>
{% endblock %}

votes/templates/votes/join.html
{% extends 'votes/base.html' %}

{% block content %}
    <div class="box">
        <form method="post">
            {% csrf_token %}

            <div class="field">
                <div class="control">
                    <label class="label" for="{{ form.token.id_for_label }}">{{ form.token.label }}</label>

                    {{ form.token }}

                    {% for error in form.token.errors %}
                        <p class="help is-danger">{{ error }}</p>
                    {% endfor %}
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <button class="button is-primary" type="submit">Beitreten</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

votes/templates/votes/list.html
{% extends 'votes/base.html' %}

{% block content %}
    {% if request.resolver_match.url_name == 'results' %}
        <div class="notification">
            <button class="delete"></button>
            Abstimmungen werden vorzeitig geschlossen, sobald alle stimmberechtigten Mitglieder daran teilgenommen
            haben.
            Entsprechende Abstimmungen werden jedoch erst nach Ablauf der regulären Frist gelistet.
        </div>
    {% endif %}

    <nav class="panel is-primary">
        <p class="panel-heading">
            {{ title }}
        </p>
        {% for decision in decision_list %}
            <a href="{% url 'votes:info' decision.id %}" class="panel-block">
        <span class="panel-icon has-text-{{ decision.state.color }}">
            <i class="{{ decision.state.icon }}" aria-hidden="true"></i>
        </span>

                <p>{{ decision.subject }}</p>
            </a>
        {% empty %}
            <p class="panel-block" disabled>Aktuell sind keine Abstimmungen verfügbar.</p>
        {% endfor %}
    </nav>
{% endblock %}

votes/templates/votes/navigation.html
<nav class="navbar" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
        <a class="navbar-item has-text-primary has-text-weight-bold" href="{% url 'votes:decisions' %}">VOTES</a>

        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarMain">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
        </a>
    </div>

    <div id="navbarMain" class="navbar-menu">
        <div class="navbar-start">
            <a class="navbar-item" href="{% url 'votes:decisions' %}">Stimme abgeben</a>
            <a class="navbar-item" href="{% url 'votes:results' %}">Ergebnisse</a>

            <div class="navbar-item has-dropdown is-hoverable">
                <a class="navbar-link">Abstimmungen</a>

                <div class="navbar-dropdown">
                    <a class="navbar-item" href="{% url 'votes:create' %}">Neu erstellen</a>
                    <a class="navbar-item" href="{% url 'votes:owned' %}">Eigene anzeigen</a>
                </div>
            </div>
        </div>

        <div class="navbar-end">
            <div class="navbar-item has-dropdown is-hoverable">
                <a class="navbar-link">Einladungen</a>

                <div class="navbar-dropdown is-right">
                    <a class="navbar-item" href="{% url 'votes:invite' %}">Neu erstellen</a>
                    <a class="navbar-item" href="{% url 'votes:invitations' %}">Alle anzeigen</a>
                </div>
            </div>

            <div class="navbar-item has-dropdown is-hoverable">
                <a class="navbar-link">Mitgliedschaften</a>

                <div class="navbar-dropdown is-right">
                    {% for team in request.user.teams.all %}
                        <div class="navbar-item">{{ team }}</div>
                    {% empty %}
                        <div class="navbar-item">Kein Mitglied eines Teams</div>
                    {% endfor %}

                    <hr class="navbar-divider">

                    <a class="navbar-item" href="{% url 'votes:join' %}">Team beitreten</a>
                    <a class="navbar-item" href="{% url 'votes:teams' %}">Alle Teams anzeigen</a>
                </div>
            </div>

            <div class="navbar-item has-dropdown is-hoverable">
                <a class="navbar-link">{{ request.user|title }}</a>

                <div class="navbar-dropdown is-right">
                    {% if request.user.get_full_name %}
                        <div class="navbar-item">{{ request.user.get_full_name }}</div>
                    {% endif %}

                    {% if request.user.email %}
                        <div class="navbar-item">{{ request.user.email }}</div>
                    {% endif %}

                    {% if request.user.get_full_name or request.user.email %}
                        <hr class="navbar-divider">
                    {% endif %}

                    <a class="navbar-item" href="{% url 'admin:password_change' %}">Passwort ändern</a>
                    <a class="navbar-item" href="{% url 'admin:logout' %}">Logout</a>
                </div>
            </div>
        </div>
    </div>
</nav>

votes/templates/votes/registration_done.html
{% extends 'votes/base.html' %}

{% block body %}
    <section class="hero is-success is-fullheight">
        <div class="hero-body">
            <div>
                <p class="title">
                    Neuer Account angelegt
                </p>
                <p class="subtitle">
                    Dein Account wurde erfolgreich erstellt. Du hast soeben von uns eine E-Mail bekommen, in welcher
                    du deinen Benutzer und Passwort findest. Logge dich damit ein und ändere anschließend dein Passwort.
                </p>
            </div>
        </div>
    </section>
{% endblock %}

votes/templates/votes/snippet_datetime_input.html
<div class="field has-addons">
    <div class="control is-expanded">
        {{ field }}
    </div>

    <div class="control">
        <button type="button" class="button set-value" value="0">
            Jetzt
        </button>
    </div>

    <div class="control">
        <button type="button" class="button set-value" value="5">
            + 5m
        </button>
    </div>

    <div class="control">
        <button type="button" class="button set-value" value="60">
            + 1h
        </button>
    </div>
</div>

votes/templates/votes/teams.html
{% extends 'votes/base.html' %}

{% block content %}
    <div class="notification">
        <button class="delete"></button>
        Die E-Mail Adressen werden nur von Mitglieder aus Organen angezeigt, bei welchem du selbst Mitglied bist.
    </div>

    {% for team in team_list %}
        <div class="box">
            <h1 class="title is-4">{{ team }}</h1>
            <table class="table is-fullwidth">
                <thead>
                <tr>
                    <th>Nr</th>
                    <th>Name</th>
                    <th>E-Mail</th>
                    <th>Eingeladen von</th>
                </tr>
                </thead>
                <tbody>
                {% for membership in team.membership_set.all %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ membership.user.get_full_name }}</td>
                        {% if request.user in membership.user.friends %}
                            <td>{{ membership.user.email }}</td>
                        {% else %}
                            <td class="has-text-grey">
                    <span class="icon is-small">
                        <i class="fas fa-user-secret fa-sm"></i>
                    </span>
                                Versteckt
                            </td>
                        {% endif %}
                        <td>{{ membership.invitation.creator.get_full_name }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    {% endfor %}
{% endblock %}

votes/templates/votes/vote.html
{% extends 'votes/base.html' %}

{% block content %}
    <div class="notification is-{{ decision.state.color }}">
        <button class="delete"></button>

        {% if decision.state.code == 'pending' %}
            Die Abstimmung beginnt erst in einiger Zeit.
            Du musst dich noch bis {{ decision.start }} gedulden.
        {% elif decision.state.code == 'open' %}
            Die Abstimmung hat begonnen.
            Du hast bis {{ decision.end }} die Möglichkeit deine Stimme abzugeben.
        {% else %}
            Die Abstimmung ist bereits zu Ende.
            Du kannst dir das Ergebnis <a href="{% url 'votes:result' decision.id %}">hier</a> einsehen.
        {% endif %}
    </div>

    {% if user_has_voted and decision.state.code != 'closed' %}
        <div class="notification is-warning">
            <button class="delete"></button>
            Du hast bereits abgestimmt!
        </div>
    {% endif %}

    <div class="box">
        <h1 class="title is-4">Stimme abgeben</h1>

        <p><strong>{{ decision.subject }}</strong></p>

        {% if entitled_to_vote %}
            <form method="post">
                {% csrf_token %}

                <fieldset{% if user_has_voted or decision.state.code != 'open' %} disabled{% endif %}>

                    <div class="field">
                        {% for radio in form.option %}
                            <div class="control">
                                <label class="radio" for="{{ radio.id_for_label }}">
                                    {{ radio.tag }}
                                    {{ radio.choice_label }}
                                </label>
                            </div>
                        {% endfor %}

                        {% for error in form.subject.errors %}
                            <p class="help is-danger">{{ error }}</p>
                        {% endfor %}
                    </div>

                    <button type="submit" class="button is-primary">Abstimmen</button>

                    {% for error in form.non_field_errors %}
                        <p class="help is-danger">{{ error }}</p>
                    {% endfor %}

                </fieldset>
            </form>
        {% else %}
            <div class="notification is-danger">
                <p class="block">
                    <strong>Du bist nicht stimmberechtigt!</strong> Solltest du fälschlicherweise doch
                    zur Stimmabgabe berechtigt sein, so wende dich an die Person, welche die Abstimmung
                    erstellt hat. Diese findest du in der Übersicht zur Abstimmung unter "Ersteller:in".
                </p>
                <a class="button is-light" href="{% url 'votes:info' decision.id %}">Zurück zur Übersicht</a>
            </div>
        {% endif %}
    </div>
{% endblock %}