mentoring/urls.py
from django.urls import path

from . import views

app_name = 'mentoring'
urlpatterns = [
    path('', views.MentorCreate.as_view(), name='mentor-create'),
    path('success/', views.MentorSuccess.as_view(), name='mentor-success'),
]

votes/urls.py
from django.urls import path

from . import views

app_name = 'votes'
urlpatterns = [
    path('', views.Decisions.as_view(), name='decisions'),
    path('create/', views.DecisionCreate.as_view(), name='create'),
    path('invitations/', views.Invitations.as_view(), name='invitations'),
    path('invitations/create/', views.InvitationCreate.as_view(), name='invite'),
    path('join/', views.JoinTeam.as_view(), name='join'),
    path('owned/', views.DecisionsOwned.as_view(), name='owned'),
    path('registration/', views.Registration.as_view(), name='registration'),
    path('registration/done/', views.RegistrationDone.as_view(), name='registration-done'),
    path('results/', views.Results.as_view(), name='results'),
    path('teams/', views.Teams.as_view(), name='teams'),
    path('<int:pk>/', views.DecisionInfo.as_view(), name='info'),
    path('<int:pk>/result/', views.ResultInfo.as_view(), name='result'),
    path('<int:pk>/vote/', views.VoteCreate.as_view(), name='vote'),
]

mentoring/models.py
from django.db import models


class Program(models.Model):
    FMB = 'MB'
    FEIT = 'EIT'
    FVST = 'VST'
    FMA = 'MA'
    FACULTIES = [
        (FMB, 'Maschinenbau'),
        (FEIT, 'Elektro- & Informationstechnik'),
        (FVST, 'Verfahrens- & Systemtechnik'),
        (FMA, 'Mathematik'),
    ]
    faculty = models.CharField(max_length=3, choices=FACULTIES)
    name = models.CharField(max_length=100)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name


class Mentor(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    phone = models.CharField(max_length=20)
    program = models.ForeignKey(Program, on_delete=models.SET_NULL, null=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.get_full_name()

    def get_full_name(self):
        return f"{self.first_name} {self.last_name}"

mentoring/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import Program, Mentor


class MentorForm(forms.ModelForm):
    privacy = forms.BooleanField(required=True, label="Datenschutz")

    class Meta:
        model = Mentor
        fields = ['first_name', 'last_name', 'email', 'phone', 'program']
        labels = {
            'first_name': "Vorname",
            'last_name': "Nachname",
            'email': "E-Mail-Adresse",
            'phone': "Mobilnummer",
            'program': "Studiengang",
        }
        widgets = {
            'first_name': forms.TextInput(attrs={'class': "input"}),
            'last_name': forms.TextInput(attrs={'class': "input"}),
            'email': forms.EmailInput(attrs={'class': "input"}),
            'phone': forms.TextInput(attrs={'class': "input"}),
            'program': forms.Select(attrs={'class': "select"}),
        }

    def __init__(self, *args, **kwargs):
        faculty = kwargs.pop('faculty', None)
        super().__init__(*args, **kwargs)
        if faculty:
            self.fields['program'].queryset = Program.objects.filter(faculty=faculty)

    def clean_first_name(self):
        data = self.cleaned_data['first_name'].title()
        return data

    def clean_last_name(self):
        data = self.cleaned_data['last_name'].title()
        return data

    def clean_email(self):
        data = self.cleaned_data['email'].lower()
        if data.split('@')[1] not in ['st.ovgu.de', 'ovgu.de']:
            raise ValidationError("Es sind nur E-Mail-Adressen der "
                                  "Otto-von-Guericke-Universität Magdeburg erlaubt.", code='blocked')
        return data

    def clean_phone(self):
        data = self.cleaned_data['phone'].replace(' ', '')

        # Define allowed values
        allowed_values = set([str(x) for x in range(10)])  # 0-9
        allowed_values.update(['+', '-', '/'])

        # Check for invalid values
        for value in data:
            if value not in allowed_values:
                raise ValidationError("Es können nur Zahlen (0-9) und einige "
                                      "Symbole (+, -, /) verwendet werden.", code='invalid')

        # Check for country code
        if data.startswith('00'):
            data = '+' + data[2:]

        if not data.startswith('+'):
            raise ValidationError("Bitte gibt deine Mobilnummer inklusive "
                                  "Ländervorwahl an. (z.B. +49, 0049)", code='ambiguous')

        # Remove unnecessary values
        data = '+' + data[1:].replace('+', '')
        data = data.replace('-', '').replace('/', '')

        return data

mentoring/views.py
from django.core.mail import send_mail
from django.views import generic

from .forms import MentorForm


class MentorCreate(generic.CreateView):
    template_name = 'mentoring/mentor_form.html'
    form_class = MentorForm
    success_url = 'success/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['privacy'] = ("Wir verwenden deine Daten um mit dir Kontakt aufzunehmen. Dein vollständiger Name und "
                              "deine E-Mail-Adresse werden außerdem zur Anmeldung für die Mentoring-Schulung benötigt. "
                              "Nach Ablauf von 12 Monaten werden sämtliche Daten von uns gelöscht.")
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['faculty'] = self.request.GET.get('faculty')
        return kwargs
    
    def form_valid(self, form):
        send_mail(
            "Bestätigung deiner Registrierung",
            """Hallo %(first_name)s,

hiermit bestätigen wir deine Registrierung als Mentor:in. 
Wir werden dich erneut kontaktieren sobald es die ersten 
Informationen zur Mentoring-Schulung gibt.

Viele Grüße
Dein Fachschaftsrat""" % form.cleaned_data,
            None,
            [form.cleaned_data['email']]
        )
        return super().form_valid(form)


class MentorSuccess(generic.TemplateView):
    template_name = 'mentoring/success.html'

mentoring/templates/mentoring/base.html
{% extends 'faking/base.html' %}

{% block section %}
    <div class="container">
        {% block content %}{% endblock %}
    </div>
{% endblock %}

mentoring/templates/mentoring/form.html
{% extends 'mentoring/base.html' %}

{% block content %}
    <div class="uk-container uk-container-small uk-margin-top uk-margin-bottom">
        <div class="uk-card uk-card-default">
            <div class="uk-card-header" style="background-color: {{ faculty.color_as_hex }};">
                <h5 class="uk-text-center" style="color: #FFFFFF">Fachschaftsrat {{ faculty.name }}</h5>
            </div>

            <div class="uk-card-body">
                <h3 class="uk-card-title uk-margin-remove-bottom">Registrierung als Mentor*in</h3>

                <p class="uk-text-small uk-margin-remove-top">
                    Eine <span class="uk-text-bold uk-text-warning">verbindliche</span> Registrierung ist bis
                    einschließlich <span class="uk-text-bold uk-text-warning">{{ faculty.deadline }}</span> möglich.
                    Sollte die Teilnahme am Mentoring-Programm unerwartet doch nicht möglich sein, muss eine Abmeldung
                    über den Fachschaftsrat erfolgen.
                </p>

                {% if form.errors %}
                    <div class="uk-alert-danger" uk-alert>
                        Bitte korrigiere alle rot markierten Fehler.
                    </div>
                {% endif %}


                <form method="post">
                    <fieldset class="uk-grid-small uk-fieldset" uk-grid>

                        {% csrf_token %}

                        {{ form.faculty }}

                        <div class="uk-width-1-2@s">
                            <label class="uk-form-label" for="{{ form.first_name.id_for_label }}">{{ form.first_name.label }}</label>

                            {{ form.first_name }}

                            {% if form.first_name.errors %}
                                {% for error in form.first_name.errors %}
                                    <p class="uk-text-small uk-text-danger uk-margin-remove">
                                        {{ error }}
                                    </p>
                                {% endfor %}
                            {% endif %}
                        </div>

                        <div class="uk-width-1-2@s">
                            <label class="uk-form-label" for="{{ form.last_name.id_for_label }}">{{ form.last_name.label }}</label>

                            {{ form.last_name }}

                            {% if form.last_name.errors %}
                                {% for error in form.last_name.errors %}
                                    <p class="uk-text-small uk-text-danger uk-margin-remove">
                                        {{ error }}
                                    </p>
                                {% endfor %}
                            {% endif %}
                        </div>

                        <div class="uk-width-1-1">
                            <label class="uk-form-label" for="{{ form.email.id_for_label }}">{{ form.email.label }}</label>

                            {{ form.email }}

                            {% if form.email.errors %}
                                {% for error in form.email.errors %}
                                    <p class="uk-text-small uk-text-danger uk-margin-remove">
                                        {{ error }}
                                    </p>
                                {% endfor %}
                            {% endif %}
                        </div>

                        <div class="uk-width-1-2@s">
                            <label class="uk-form-label" for="{{ form.phone.id_for_label }}">{{ form.phone.label }}</label>

                            {{ form.phone }}

                            {% if form.phone.errors %}
                                {% for error in form.phone.errors %}
                                    <p class="uk-text-small uk-text-danger uk-margin-remove">
                                        {{ error }}
                                    </p>
                                {% endfor %}
                            {% endif %}
                        </div>

                        <div class="uk-width-1-2@s">
                            <label class="uk-form-label" for="{{ form.program.id_for_label }}">{{ form.program.label }}</label>

                            {{ form.program }}

                            {% if form.program.errors %}
                                {% for error in form.program.errors %}
                                    <p class="uk-text-small uk-text-danger uk-margin-remove">
                                        {{ error }}
                                    </p>
                                {% endfor %}
                            {% endif %}
                        </div>

                        <div class="uk-width-1-2@s">
                            <label class="uk-form-label" for="{{ form.qualification.id_for_label }}">
                                {{ form.qualification }} {{ form.qualification.label }}
                            </label><br>
                            <label class="uk-form-label" for="{{ form.supervision.id_for_label }}">
                                {{ form.supervision }} {{ form.supervision.label }}
                            </label>

                            {% if form.qualification.errors or form.supervision.erros %}
                                {% for error in form.qualification.errors %}
                                    <p class="uk-text-small uk-text-danger uk-margin-remove">
                                        {{ error }}
                                    </p>
                                {% endfor %}

                                {% for error in form.supervision.errors %}
                                    <p class="uk-text-small uk-text-danger uk-margin-remove">
                                        {{ error }}
                                    </p>
                                {% endfor %}
                            {% endif %}
                        </div>

                        <div class="uk-width-1-2@s">
                            <label class="uk-form-label" for="id_privacy">
                                <input id="id_privacy" class="uk-checkbox" type="checkbox" name="privacy"> Einwilligung zur <a target="_blank" class="uk-link" href="https://stura-md.de/datenschutz/">Datenschutzerklärung</a>
                            </label>

                            {% if form.privacy.errors %}
                                {% for error in form.privacy.errors %}
                                    <p class="uk-text-small uk-text-danger uk-margin-remove">
                                        {{ error }}
                                    </p>
                                {% endfor %}
                            {% endif %}
                        </div>
                    </fieldset>

                    <button class="uk-button uk-button-default uk-margin-top" type="submit">Registrieren</button>

                    {% if form.non_field_errors %}
                        {% for error in form.non_field_errors %}
                            <p class="uk-text-danger">{{ error }}</p>
                        {% endfor %}
                    {% endif %}
                </form>
            </div>
            <div class="uk-card-footer">
                <p class="uk-text-meta uk-text-italic">Die angegebenen Daten werden für maximal 12 Monate gespeichert und anschließend gelöscht. Es werden Vorname, Nachname sowie E-Mail Adresse zur Anmeldung für die Schulungen an die <a target="_blank" class="uk-link" href="https://www.ovgu.de/">Otto-von-Guericke-Universität Magdeburg</a> weiter gegeben.</p>
            </div>
        </div>
    </div>
{% endblock %}

mentoring/templates/mentoring/mentor_form.html
{% extends 'mentoring/base.html' %}

{% block content %}
    <p class="title">Registrierung als Mentor:in</p>

    {% include 'mentoring/snippets/privacy_info.html' with message=privacy %}

    <div class="box">
        <form method="post">

            {% csrf_token %}

            <div class="columns is-multiline">
                <div class="column is-half">
                    {% include 'mentoring/forms/input_or_textarea.html' with field=form.first_name %}
                </div>

                <div class="column is-half">
                    {% include 'mentoring/forms/input_or_textarea.html' with field=form.last_name %}
                </div>

                <div class="column is-half">
                    {% include 'mentoring/forms/input_or_textarea.html' with field=form.email %}
                </div>

                <div class="column is-half">
                    {% include 'mentoring/forms/input_or_textarea.html' with field=form.phone %}
                </div>

                <div class="column is-full">
                    {% include 'mentoring/forms/select.html' with field=form.program %}
                </div>

                <div class="column is-full">
                    {% include 'mentoring/forms/checkbox_privacy.html' with field=form.privacy %}
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <button type="submit" class="button is-primary">Registrieren</button>
                </div>
                {% for error in form.non_field_errors %}
                    <p class="help is-danger">{{ error }}</p>
                {% endfor %}
            </div>
        </form>
    </div>
{% endblock %}

mentoring/templates/mentoring/success.html
{% extends 'mentoring/base.html' %}

{% block body %}
    <section class="hero is-success is-fullheight">
        <div class="hero-body">
            <div>
                <p class="title">
                    Alles fertig.
                </p>
                <p class="subtitle">
                    Du hast dich erfolgreich als Mentor:in registriert. Wir haben dir soeben auch noch eine E-Mail
                    zur Bestätigung geschickt. Solltest du dich doch wieder abmelden wollen, melde dich bitte per
                    E-Mail bei deinem Fachschaftsrat.
                </p>
            </div>
        </div>
    </section>
{% endblock %}