faking/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import render

urlpatterns = [
    path('', lambda request: render(request, 'faking/landing_page.html'), name='landing_page'),
    path('mentoring/', include('mentoring.urls')),
    path('votes/', include('votes.urls')),
    path('admin/', admin.site.urls),
]

votes/urls.py
from django.urls import path

from . import views

app_name = 'votes'
urlpatterns = [
    path('', views.Decisions.as_view(), name='decisions'),
    path('create/', views.DecisionCreate.as_view(), name='create'),
    path('invitations/', views.Invitations.as_view(), name='invitations'),
    path('invitations/create/', views.InvitationCreate.as_view(), name='invite'),
    path('join/', views.JoinTeam.as_view(), name='join'),
    path('owned/', views.DecisionsOwned.as_view(), name='owned'),
    path('registration/', views.Registration.as_view(), name='registration'),
    path('registration/done/', views.RegistrationDone.as_view(), name='registration-done'),
    path('results/', views.Results.as_view(), name='results'),
    path('teams/', views.Teams.as_view(), name='teams'),
    path('<int:pk>/', views.DecisionInfo.as_view(), name='info'),
    path('<int:pk>/result/', views.ResultInfo.as_view(), name='result'),
    path('<int:pk>/vote/', views.VoteCreate.as_view(), name='vote'),
]

faking/templates/faking/base.html
<!DOCTYPE html>{% load static %}
<html lang="de">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}FakIng{% endblock %}</title>

    <!-- Styles -->
    <link rel="stylesheet" type="text/css" href="{% static 'faking/css/bulma.min.css' %}">

    <!-- Scripts -->
    {% block scripts %}
        <script src="{% static 'faking/js/fontawesome.min.js' %}"></script>
    {% endblock %}
</head>
<body>
{% block body %}
    <section class="section">
        {% block section %}{% endblock %}
    </section>

    {% include 'faking/footer.html' %}
{% endblock %}
</body>
</html>

faking/templates/faking/base_hero.html
{% extends 'faking/base.html' %}

{% block body %}
<section class="hero is-fullheight {% block hero-color %}is-success{% endblock %}">
    <div class="hero-body">
        <div class="container">
            <p class="title">
                {% block hero-title %}{% endblock %}
            </p>

            <p class="subtitle">
                {% block hero-subtitle %}{% endblock %}
            </p>
        </div>
    </div>
</section>
{% endblock %}

faking/templates/faking/footer.html
<footer class="footer has-background-white">
    <div class="content has-text-centered">
        <p>
            <strong>Fakultät der Ingenieure</strong><br>
            &#169; {% now 'Y' %} <a href="https://farafmb.de">Fachschaftsrat Maschinenbau</a><br>
            <a href="https://stura-md.de/impressum/">Impressum</a> | <a href="https://stura-md.de/datenschutz/">Datenschutz</a>
        </p>
    </div>
</footer>

faking/templates/faking/landing_page.html
{% extends 'faking/base.html' %}

{% load static %}

{% block body %}
<section class="hero is-fullheight">
    <div class="hero-head">
        <nav class="navbar">
            <div class="container">
                <div class="navbar-brand">
                    <span class="navbar-burger" data-target="navbarMenu">
                        <span></span>
                        <span></span>
                        <span></span>
                    </span>
                </div>

                <div id="navbarMenu" class="navbar-menu">
                    <div class="navbar-end">
                        <div class="navbar-item dropdown is-right is-hoverable">
                            <div class="dropdown-trigger">
                                <a href="https://pad.faking.cool" class="has-text-grey-dark">
                                    <span class="icon-text">
                                        <span class="icon">
                                            <i class="fas fa-sticky-note"></i>
                                        </span>
                                        <span>Pad</span>
                                    </span>
                                </a>
                            </div>
                            <div class="dropdown-menu" id="dropdown-pad" role="menu">
                                <div class="dropdown-content">
                                    <div class="dropdown-item">
                                        Kollaboratives Tool zum gemeinsamen Schreiben von schnellen Notizen.
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="navbar-item dropdown is-right is-hoverable">
                            <div class="dropdown-trigger">
                                <a href="https://cloud.faking.cool" class="has-text-grey-dark">
                                    <span class="icon-text">
                                        <span class="icon">
                                            <i class="fas fa-cloud"></i>
                                        </span>
                                        <span>Cloud</span>
                                    </span>
                                </a>
                            </div>
                            <div class="dropdown-menu" id="dropdown-cloud" role="menu">
                                <div class="dropdown-content">
                                    <div class="dropdown-item">
                                        Sammlung von Gedächtnisprotokollen für Module an der FMB, FEIT und FVST.
                                    </div>
                                    <hr class="dropdown-divider">
                                    <div class="dropdown-item">
                                        Eine Registrierung wird benötigt.
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="navbar-item dropdown is-right is-hoverable">
                            <div class="dropdown-trigger">
                                <a href="{% url 'votes:decisions' %}" class="has-text-grey-dark">
                                    <span class="icon-text">
                                        <span class="icon">
                                            <i class="fas fa-vote-yea"></i>
                                        </span>
                                        <span>Vote</span>
                                    </span>
                                </a>
                            </div>
                            <div class="dropdown-menu" id="dropdown-vote" role="menu">
                                <div class="dropdown-content">
                                    <div class="dropdown-item">
                                        Tool zum Durchführen von Abstimmungen.
                                    </div>
                                    <hr class="dropdown-divider">
                                    <div class="dropdown-item">
                                        Zugriff nur für Mitglieder eines Fachschaftsrates.
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </nav>
    </div>

    <div class="hero-body">
        <div class="container is-max-desktop has-text-centered">
            <figure class="image is-128x128 mx-auto mb-3">
                <img src="{% static 'logo.png' %}" alt="Logo">
            </figure>

            <p class="title">FakIng ['fʌkɪŋ]</p>
            <p class="subtitle">Fakultät der Ingenieure</p>

            <p>
                Die <strong>Fakultät der Ingenieure</strong> ist ein Zusammenschluss der Fachschaftsräte
                <a target="_blank" href="https://farafmb.de">Maschinenbau</a>,
                <a target="_blank" href="https://www.farafeit.de">Elektro- & Informationstechnik</a> sowie
                <a target="_blank" href="https://www.farafvst.ovgu.de">Verfahrens- & Systemtechnik</a> der
                <a target="_blank" href="https://www.ovgu.de">Otto-von-Guericke-Universität</a> Magdeburg. Diese
                Kooperation bündelt Ressourcen für gemeinsame Ideen & Ziele, welche für alle Studierenden der drei
                Fakultäten von Nutzen sind.
            </p>
        </div>
    </div>

    <div class="hero-foot">
        <nav class="tabs">
            <div class="container">
                <ul>
                    <li><a href="https://stura-md.de/impressum/">Impressum</a></li>
                    <li><a href="https://stura-md.de/datenschutz/">Datenschutz</a></li>
                </ul>
            </div>
        </nav>
    </div>
</section>
{% endblock %}